# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import transcribe

class Ui_QWrite(object):
    def setupUi(self, QWrite):
        QWrite.setObjectName("QWrite")
        QWrite.resize(405, 196)
        QWrite.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(QWrite)
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QLabel(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(30, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.start.setFont(font)
        self.start.setScaledContents(True)
        self.start.setAlignment(QtCore.Qt.AlignCenter)
        self.start.setObjectName("start")
        self.theName = QtWidgets.QLabel(self.centralwidget)
        self.theName.setGeometry(QtCore.QRect(170, 30, 221, 101))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.theName.setFont(font)
        self.theName.setScaledContents(True)
        self.theName.setAlignment(QtCore.Qt.AlignCenter)
        self.theName.setObjectName("theName")
        self.start_2 = QtWidgets.QLabel(self.centralwidget)
        self.start_2.setGeometry(QtCore.QRect(30, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_2.setFont(font)
        self.start_2.setScaledContents(True)
        self.start_2.setAlignment(QtCore.Qt.AlignCenter)
        self.start_2.setObjectName("start_2")
        self.start_3 = QtWidgets.QLabel(self.centralwidget)
        self.start_3.setGeometry(QtCore.QRect(30, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.start_3.setFont(font)
        self.start_3.setScaledContents(True)
        self.start_3.setAlignment(QtCore.Qt.AlignCenter)
        self.start_3.setObjectName("start_3")
        self.start_4 = QtWidgets.QLabel(self.centralwidget)
        self.start_4.setGeometry(QtCore.QRect(30, 100, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.start_4.setFont(font)
        self.start_4.setScaledContents(True)
        self.start_4.setAlignment(QtCore.Qt.AlignCenter)
        self.start_4.setObjectName("start_4")
        self.start_5 = QtWidgets.QLabel(self.centralwidget)
        self.start_5.setGeometry(QtCore.QRect(6, 130, 165, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.start_5.setFont(font)
        self.start_5.setScaledContents(True)
        self.start_5.setAlignment(QtCore.Qt.AlignCenter)
        self.start_5.setObjectName("start_5")
        QWrite.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QWrite)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 405, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        QWrite.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QWrite)
        self.statusbar.setObjectName("statusbar")
        QWrite.setStatusBar(self.statusbar)
        self.actionStart_Recording = QtWidgets.QAction(QWrite)
        self.actionStart_Recording.setObjectName("actionStart_Recording")
        self.actionStop_Recording = QtWidgets.QAction(QWrite)
        self.actionStop_Recording.setObjectName("actionStop_Recording")
        self.menuFile.addAction(self.actionStart_Recording)
        self.menuFile.addAction(self.actionStop_Recording)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(QWrite)
        QtCore.QMetaObject.connectSlotsByName(QWrite)

        self.actionStart_Recording.triggered.connect(lambda: self.starts())
        self.actionStop_Recording.triggered.connect(lambda: self.stops())

    def retranslateUi(self, QWrite):
        _translate = QtCore.QCoreApplication.translate
        QWrite.setWindowTitle(_translate("QWrite", "QuickWrite"))
        self.start.setText(_translate("QWrite", "Start Recording"))
        self.theName.setText(_translate("QWrite", "QuickWrite"))
        self.start_2.setText(_translate("QWrite", "Stop Recording"))
        self.start_3.setText(_translate("QWrite", "CTRL + R"))
        self.start_4.setText(_translate("QWrite", "CTRL + SHIFT + R"))
        self.start_5.setText(_translate("QWrite", "or just say \"Stop Recording.\""))
        self.menuFile.setTitle(_translate("QWrite", "File"))
        self.actionStart_Recording.setText(_translate("QWrite", "Start Recording"))
        self.actionStart_Recording.setShortcut(_translate("QWrite", "Ctrl+R"))
        self.actionStop_Recording.setText(_translate("QWrite", "Stop Recording"))
        self.actionStop_Recording.setShortcut(_translate("QWrite", "Ctrl+Shift+R"))
    
    def starts(self):
        transcribe.run()
    
    def stops(self):
        transcribe.transcribe().stop()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QWrite = QtWidgets.QMainWindow()
    ui = Ui_QWrite()
    ui.setupUi(QWrite)
    QWrite.show()
    sys.exit(app.exec_())